name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalar dependencias
        run: |
          cd calculadora
          npm install

      - name: Ejecutar Linter
        run: |
          cd calculadora
          npm run lint
